# Generated by Django 5.1.4 on 2025-01-01 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='paymentDetail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderItemPayment', to='orders.payment'),
        ),
    ]
