# Generated by Django 5.1.4 on 2025-01-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_paymentdetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returnRequestId', models.CharField(max_length=100, unique=True)),
                ('reason', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundId', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returnRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.returnrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returnRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request_statuses', to='orders.returnrequest')),
            ],
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='allStatus',
            field=models.ManyToManyField(blank=True, related_name='all_return_requests', to='orders.returnrequeststatus'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='currentStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_request_status', to='orders.returnrequeststatus'),
        ),
    ]
