# Generated by Django 5.1.4 on 2025-01-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_returnrequest_refund_returnrequeststatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='description',
            field=models.TextField(default='Hello New Added'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], max_length=100),
        ),
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
