# Generated by Django 5.1.4 on 2025-01-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_courior_orderitem_trackingid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Approved', 'Return Approved'), ('Return Rejected', 'Return Rejected'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], max_length=100),
        ),
    ]
