# Generated by Django 5.1.4 on 2025-01-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitemstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='paymentMethod',
            field=models.CharField(default='Online', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refund',
            name='transactionId',
            field=models.CharField(default='trx-1234', max_length=100),
            preserve_default=False,
        ),
    ]
