# Generated by Django 5.1.4 on 2025-01-04 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_returnrequeststatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderItemRefund', to='orders.refund'),
        ),
    ]
