# Generated by Django 5.0.7 on 2025-01-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequeststatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Returned', 'Returned'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], max_length=100),
        ),
    ]
