# Generated by Django 5.0.7 on 2025-01-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_returnrequeststatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Approved', 'Return Approved'), ('Rejected', 'Return Rejected'), ('Returned', 'Returned'), ('Refunded', 'Refunded')], max_length=100),
        ),
    ]
