# Generated by Django 5.1.4 on 2025-01-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
