# Generated by Django 5.0.7 on 2025-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayout',
            name='isRefunded',
            field=models.BooleanField(default=False),
        ),
    ]
