# Generated by Django 5.1.4 on 2025-01-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_default_variants'),
        ('products', '0003_add_default_variants'),
    ]

    operations = [
    ]
